# Generated by Django 5.0.6 on 2024-05-18 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('fullname', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=30)),
            ],
        ),
    ]
