# Generated by Django 5.0.6 on 2024-05-26 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_analysis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useranalysis',
            name='fullname',
            field=models.CharField(max_length=50, verbose_name='имя'),
        ),
        migrations.AlterField(
            model_name='useranalysis',
            name='phone_number',
            field=models.CharField(max_length=30, verbose_name='номер телефона'),
        ),
    ]
