# Generated by Django 5.0.6 on 2024-05-26 06:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name_category',
            field=models.CharField(max_length=30, unique=True, verbose_name='наименование категории'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='photo',
            field=models.ImageField(upload_to='uploads/%Y/%m/%d/', verbose_name='фото'),
        ),
        migrations.AlterField(
            model_name='price',
            name='car',
            field=models.PositiveIntegerField(verbose_name='легковой автомобиль'),
        ),
        migrations.AlterField(
            model_name='price',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='about_us.category', verbose_name='категория'),
        ),
        migrations.AlterField(
            model_name='price',
            name='jeep',
            field=models.PositiveIntegerField(verbose_name='джип'),
        ),
        migrations.AlterField(
            model_name='price',
            name='minivan',
            field=models.PositiveIntegerField(verbose_name='минивэн'),
        ),
        migrations.AlterField(
            model_name='price',
            name='name_service',
            field=models.CharField(max_length=30, unique=True, verbose_name='наименование сервиса'),
        ),
    ]
