# Generated by Django 5.0.6 on 2024-05-28 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0003_price_describe_service_alter_price_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='describe_service',
            field=models.CharField(default='Описание', max_length=500, verbose_name='описание сервиса'),
        ),
    ]
