# Generated by Django 5.0.6 on 2024-05-22 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recording_online', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordingonline',
            name='fullname',
            field=models.CharField(default='Василиев Василий Васильевич', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recordingonline',
            name='phone_number',
            field=models.CharField(default='+375 29 500 00 00', max_length=30),
            preserve_default=False,
        ),
    ]
