# Generated by Django 5.0.6 on 2024-05-26 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recording_online', '0002_recordingonline_fullname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordingonline',
            name='car_number',
            field=models.CharField(default='MI 7502', max_length=30, verbose_name='номер автомобиля'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recordingonline',
            name='date',
            field=models.DateField(verbose_name='дата'),
        ),
        migrations.AlterField(
            model_name='recordingonline',
            name='fullname',
            field=models.CharField(max_length=50, verbose_name='имя'),
        ),
        migrations.AlterField(
            model_name='recordingonline',
            name='phone_number',
            field=models.CharField(max_length=30, verbose_name='номер телефона'),
        ),
        migrations.AlterField(
            model_name='recordingonline',
            name='time',
            field=models.TimeField(verbose_name='время'),
        ),
    ]
